In [1]:
import numpy as np


In [2]:
from sklearn.cross_validation import train_test_split

c:\python 3.6.5\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
X, Y = np.arange(10).reshape((5,2)), range(5)

In [8]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
list(Y)

[0, 1, 2, 3, 4]

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3 )

In [14]:
X_train

array([[0, 1],
       [6, 7],
       [2, 3]])

In [15]:
X_test

array([[4, 5],
       [8, 9]])

In [17]:
Y_test

[2, 4]

In [18]:
Y_train

[0, 3, 1]